jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Poetry repository
        run: |
          poetry config repositories.github https://pypi.org/simple
          poetry config http-basic.pypi ${{ secrets.PYPI_USERNAME }} ${{ secrets.PYPI_PASSWORD }}
